-- Daone 管理后台 PostgreSQL 增量 SQL
-- 目标：在复用前台既有业务表的基础上，补齐当前管理后台所需的最小表结构。
-- 适用：PostgreSQL 12+

BEGIN;

-- 1. 复用前台表所需的最小扩展

ALTER TABLE workflow
    ADD COLUMN IF NOT EXISTS attributes JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMENT ON COLUMN workflow.attributes IS '扩展字段。后台工作流模板使用 attributes.adminTemplate=true 标记，其他后台字段如 workflowCode/categoryCode/nodeCount/ownerName/status 也存于此。';

CREATE INDEX IF NOT EXISTS idx_workflow_admin_template
    ON workflow ((attributes ->> 'status'), updated_at)
    WHERE deleted = 0
      AND attributes @> '{"adminTemplate": true}'::jsonb;

ALTER TABLE inspiration
    ADD COLUMN IF NOT EXISTS prompt TEXT,
    ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS attributes JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMENT ON COLUMN inspiration.prompt IS '创作提示词，用于管理后台灵感发现页面。';
COMMENT ON COLUMN inspiration.attributes IS '扩展字段。';

CREATE INDEX IF NOT EXISTS idx_inspiration_deleted_status
    ON inspiration (deleted, status, updated_at);

ALTER TABLE prompt_template
    ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS attributes JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMENT ON COLUMN prompt_template.attributes IS '扩展字段。';

CREATE INDEX IF NOT EXISTS idx_prompt_template_deleted_status
    ON prompt_template (deleted, status, updated_at);

ALTER TABLE model_config
    ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS attributes JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMENT ON COLUMN model_config.attributes IS '扩展字段。';

CREATE INDEX IF NOT EXISTS idx_model_config_deleted_status
    ON model_config (deleted, status, updated_at);

ALTER TABLE subscription_plan
    ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS attributes JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMENT ON COLUMN subscription_plan.attributes IS '扩展字段。';

CREATE INDEX IF NOT EXISTS idx_subscription_plan_deleted_status
    ON subscription_plan (deleted, status, updated_at);


-- 2. 开票申请表：后台开票列表使用

CREATE TABLE IF NOT EXISTS invoice_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(40) NOT NULL,
    user_id BIGINT NOT NULL,
    order_no VARCHAR(40) NOT NULL,
    invoice_title VARCHAR(128) NOT NULL,
    tax_no VARCHAR(64) NOT NULL,
    invoice_type VARCHAR(32) NOT NULL,
    amount_fen BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    email VARCHAR(128),
    receiver_name VARCHAR(64),
    receiver_phone VARCHAR(20),
    receiver_address VARCHAR(500),
    reject_reason VARCHAR(500),
    issued_at TIMESTAMP,
    invoice_file_asset_id BIGINT,
    express_company VARCHAR(64),
    express_no VARCHAR(64),
    gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb
);

COMMENT ON TABLE invoice_application IS '开票申请表，管理后台开票列表使用。';
COMMENT ON COLUMN invoice_application.id IS '自增主键。';
COMMENT ON COLUMN invoice_application.gmt_create IS '记录创建时间。';
COMMENT ON COLUMN invoice_application.gmt_modified IS '记录修改时间。';
COMMENT ON COLUMN invoice_application.deleted IS '逻辑删除标记。';
COMMENT ON COLUMN invoice_application.attributes IS '扩展字段，JSON 结构。';
COMMENT ON COLUMN invoice_application.invoice_type IS '发票类型：VAT_NORMAL、VAT_SPECIAL。';
COMMENT ON COLUMN invoice_application.status IS '状态：PENDING、PROCESSING、ISSUED、REJECTED、CANCELLED。';

CREATE UNIQUE INDEX IF NOT EXISTS uk_invoice_application_no
    ON invoice_application (invoice_no)
    WHERE deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_invoice_application_order
    ON invoice_application (order_no);

CREATE INDEX IF NOT EXISTS idx_invoice_application_user_create
    ON invoice_application (user_id, gmt_create DESC);

CREATE INDEX IF NOT EXISTS idx_invoice_application_status_create
    ON invoice_application (status, gmt_create DESC)
    WHERE deleted = FALSE;


-- 3. 内容分类表：后台分类管理使用

CREATE TABLE IF NOT EXISTS content_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(32) NOT NULL,
    category_name VARCHAR(64) NOT NULL,
    scope VARCHAR(32) NOT NULL,
    parent_code VARCHAR(32),
    sort_no INT NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
    gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb
);

COMMENT ON TABLE content_category IS '内容分类表，管理灵感发现、模板和后台工作流分类。';
COMMENT ON COLUMN content_category.id IS '自增主键。';
COMMENT ON COLUMN content_category.gmt_create IS '记录创建时间。';
COMMENT ON COLUMN content_category.gmt_modified IS '记录修改时间。';
COMMENT ON COLUMN content_category.deleted IS '逻辑删除标记。';
COMMENT ON COLUMN content_category.attributes IS '扩展字段，JSON 结构。';
COMMENT ON COLUMN content_category.scope IS '使用范围：ALL、INSPIRATION、TEMPLATE。';
COMMENT ON COLUMN content_category.status IS '状态：ENABLED、DISABLED。';

CREATE UNIQUE INDEX IF NOT EXISTS uk_content_category_code
    ON content_category (category_code)
    WHERE deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_content_category_scope_status
    ON content_category (scope, status, sort_no)
    WHERE deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_content_category_parent
    ON content_category (parent_code, sort_no)
    WHERE deleted = FALSE;


-- 4. 后台操作日志表：所有后台写操作记录

CREATE TABLE IF NOT EXISTS admin_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT NOT NULL,
    action VARCHAR(64) NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id VARCHAR(64),
    request_method VARCHAR(10),
    request_path VARCHAR(255),
    before_json JSONB,
    after_json JSONB,
    remark VARCHAR(500),
    ip VARCHAR(64),
    user_agent VARCHAR(500),
    gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb
);

COMMENT ON TABLE admin_operation_log IS '后台操作日志表，记录管理后台写操作。';
COMMENT ON COLUMN admin_operation_log.id IS '自增主键。';
COMMENT ON COLUMN admin_operation_log.gmt_create IS '记录创建时间。';
COMMENT ON COLUMN admin_operation_log.gmt_modified IS '记录修改时间。';
COMMENT ON COLUMN admin_operation_log.deleted IS '逻辑删除标记。';
COMMENT ON COLUMN admin_operation_log.attributes IS '扩展字段，JSON 结构。';

CREATE INDEX IF NOT EXISTS idx_admin_operation_log_admin_create
    ON admin_operation_log (admin_user_id, gmt_create DESC);

CREATE INDEX IF NOT EXISTS idx_admin_operation_log_target
    ON admin_operation_log (target_type, target_id);

CREATE INDEX IF NOT EXISTS idx_admin_operation_log_action_create
    ON admin_operation_log (action, gmt_create DESC);

COMMIT;
