import { store, reseedStore } from "../db/memoryStore.js";
import { appConfig } from "../config/env.js";

const BUSINESS_STORE_KEYS = [
  "users",
  "projects",
  "canvases",
  "canvasElementGroups",
  "versions",
  "shares",
  "assets",
  "favorites",
  "generationTasks",
  "chatSessions",
  "chatMessages",
  "workflows",
  "orders",
  "transactions",
  "subscriptions",
  "pointAccounts",
  "pointLedgers",
  "inspirations",
  "plans",
  "prices",
  "models",
  "promptTemplates",
  "invoiceApplications",
  "contentCategories",
  "adminOperationLogs"
];

const SEED_BACKED_KEYS = [
  "plans",
  "prices",
  "models",
  "inspirations",
  "workflows",
  "contentCategories",
  "invoiceApplications",
  "promptTemplates",
  "assets"
];

export async function ensurePostgresBusinessSchema(pool) {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS user_account (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      phone VARCHAR(20),
      wechat_open_id VARCHAR(64),
      nickname VARCHAR(64) NOT NULL,
      avatar_url VARCHAR(500),
      email VARCHAR(128),
      gender VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN',
      birthday DATE,
      status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
      role VARCHAR(32) NOT NULL DEFAULT 'USER',
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL,
      CONSTRAINT uk_user_phone UNIQUE (phone),
      CONSTRAINT uk_user_wechat UNIQUE (wechat_open_id)
    );

    CREATE TABLE IF NOT EXISTS project (
      id BIGINT PRIMARY KEY,
      user_id BIGINT NOT NULL,
      title VARCHAR(128) NOT NULL,
      cover_asset_id BIGINT,
      status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_project_user_updated ON project(user_id, updated_at);

    CREATE TABLE IF NOT EXISTS project_canvas (
      project_id BIGINT PRIMARY KEY,
      canvas_json TEXT NOT NULL,
      revision BIGINT NOT NULL DEFAULT 0,
      updated_at TIMESTAMP NOT NULL
    );

    CREATE TABLE IF NOT EXISTS canvas_element_group (
      id BIGINT PRIMARY KEY,
      user_id BIGINT NOT NULL,
      project_id BIGINT NOT NULL,
      name VARCHAR(128) NOT NULL,
      description VARCHAR(500),
      structure_json TEXT NOT NULL,
      deleted SMALLINT NOT NULL DEFAULT 0,
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_canvas_element_group_project ON canvas_element_group(project_id, deleted, updated_at);
    CREATE INDEX IF NOT EXISTS idx_canvas_element_group_user ON canvas_element_group(user_id, updated_at);

    CREATE TABLE IF NOT EXISTS project_version (
      id BIGINT PRIMARY KEY,
      project_id BIGINT NOT NULL,
      version_no INT NOT NULL,
      canvas_json TEXT NOT NULL,
      created_at TIMESTAMP NOT NULL,
      CONSTRAINT uk_project_version UNIQUE (project_id, version_no)
    );

    CREATE TABLE IF NOT EXISTS project_share (
      id BIGINT PRIMARY KEY,
      share_code VARCHAR(40) NOT NULL,
      project_id BIGINT NOT NULL,
      user_id BIGINT NOT NULL,
      status VARCHAR(16) NOT NULL,
      expire_at TIMESTAMP NOT NULL,
      created_at TIMESTAMP NOT NULL,
      CONSTRAINT uk_project_share_code UNIQUE (share_code)
    );
    ALTER TABLE project_share ADD COLUMN IF NOT EXISTS title VARCHAR(128);
    ALTER TABLE project_share ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
    CREATE INDEX IF NOT EXISTS idx_project_share_project ON project_share(project_id, status);

    CREATE TABLE IF NOT EXISTS asset (
      id BIGINT PRIMARY KEY,
      user_id BIGINT NOT NULL,
      project_id BIGINT,
      type VARCHAR(16) NOT NULL,
      source VARCHAR(16) NOT NULL,
      file_name VARCHAR(255) NOT NULL,
      object_key VARCHAR(500),
      content_type VARCHAR(100),
      file_size BIGINT,
      width INT,
      height INT,
      duration_seconds INT,
      review_status VARCHAR(16) NOT NULL,
      deleted SMALLINT NOT NULL DEFAULT 0,
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL
    );
    ALTER TABLE asset ADD COLUMN IF NOT EXISTS preview_url VARCHAR(1000);
    ALTER TABLE asset ADD COLUMN IF NOT EXISTS tags_json TEXT;
    CREATE INDEX IF NOT EXISTS idx_asset_user_created ON asset(user_id, created_at);

    CREATE TABLE IF NOT EXISTS asset_favorite (
      id BIGINT PRIMARY KEY,
      user_id BIGINT NOT NULL,
      asset_id BIGINT NOT NULL,
      created_at TIMESTAMP NOT NULL,
      CONSTRAINT uk_asset_favorite UNIQUE (user_id, asset_id)
    );

    CREATE TABLE IF NOT EXISTS generation_task (
      id BIGINT PRIMARY KEY,
      user_id BIGINT NOT NULL,
      project_id BIGINT,
      node_id VARCHAR(64),
      task_type VARCHAR(16) NOT NULL,
      capability_code VARCHAR(64) NOT NULL,
      prompt TEXT,
      parameters_json TEXT,
      reference_asset_ids_json TEXT,
      idempotency_key VARCHAR(64) NOT NULL,
      provider_task_id VARCHAR(128),
      status VARCHAR(16) NOT NULL,
      progress INT NOT NULL DEFAULT 0,
      estimated_points BIGINT NOT NULL DEFAULT 0,
      actual_points BIGINT,
      error_code VARCHAR(64),
      error_message VARCHAR(500),
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL
    );
    ALTER TABLE generation_task ADD COLUMN IF NOT EXISTS results_json TEXT;
    CREATE INDEX IF NOT EXISTS idx_task_user_status_created ON generation_task(user_id, status, created_at);
    CREATE UNIQUE INDEX IF NOT EXISTS uk_generation_idempotency ON generation_task(user_id, idempotency_key);

    CREATE TABLE IF NOT EXISTS generation_result (
      id BIGINT PRIMARY KEY,
      task_id BIGINT NOT NULL,
      asset_id BIGINT NOT NULL,
      sort_no INT NOT NULL DEFAULT 0,
      created_at TIMESTAMP NOT NULL
    );

    CREATE TABLE IF NOT EXISTS workflow (
      id BIGINT PRIMARY KEY,
      user_id BIGINT NOT NULL,
      name VARCHAR(128) NOT NULL,
      description VARCHAR(500),
      cover_asset_id BIGINT,
      workflow_json TEXT NOT NULL,
      deleted SMALLINT NOT NULL DEFAULT 0,
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL
    );
    ALTER TABLE workflow ADD COLUMN IF NOT EXISTS attributes JSONB NOT NULL DEFAULT '{}'::jsonb;

    CREATE TABLE IF NOT EXISTS chat_session (
      id BIGINT PRIMARY KEY,
      user_id BIGINT NOT NULL,
      project_id BIGINT NOT NULL,
      title VARCHAR(128) NOT NULL,
      deleted SMALLINT NOT NULL DEFAULT 0,
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL
    );

    CREATE TABLE IF NOT EXISTS chat_message (
      id BIGINT PRIMARY KEY,
      session_id BIGINT NOT NULL,
      role VARCHAR(16) NOT NULL,
      content TEXT NOT NULL,
      attachment_asset_ids_json TEXT,
      generation_task_ids_json TEXT,
      created_at TIMESTAMP NOT NULL
    );

    CREATE TABLE IF NOT EXISTS point_account (
      user_id BIGINT PRIMARY KEY,
      available_points BIGINT NOT NULL DEFAULT 0,
      frozen_points BIGINT NOT NULL DEFAULT 0,
      granted_total BIGINT NOT NULL DEFAULT 0,
      version INT NOT NULL DEFAULT 0,
      updated_at TIMESTAMP NOT NULL
    );

    CREATE TABLE IF NOT EXISTS point_ledger (
      id BIGINT PRIMARY KEY,
      user_id BIGINT NOT NULL,
      action VARCHAR(16) NOT NULL,
      amount BIGINT NOT NULL,
      balance_after BIGINT NOT NULL,
      biz_type VARCHAR(32) NOT NULL,
      biz_id VARCHAR(64) NOT NULL,
      description VARCHAR(255),
      created_at TIMESTAMP NOT NULL,
      CONSTRAINT uk_point_biz UNIQUE (user_id, biz_type, biz_id, action)
    );

    CREATE TABLE IF NOT EXISTS subscription_plan (
      id BIGINT PRIMARY KEY,
      plan_code VARCHAR(32) NOT NULL,
      plan_name VARCHAR(64) NOT NULL,
      description VARCHAR(500),
      benefits_json TEXT,
      status VARCHAR(16) NOT NULL,
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL,
      CONSTRAINT uk_plan_code UNIQUE (plan_code)
    );
    ALTER TABLE subscription_plan ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE subscription_plan ADD COLUMN IF NOT EXISTS attributes JSONB NOT NULL DEFAULT '{}'::jsonb;

    CREATE TABLE IF NOT EXISTS subscription_plan_price (
      id BIGINT PRIMARY KEY,
      plan_id BIGINT NOT NULL,
      price_code VARCHAR(32) NOT NULL,
      cycle_unit VARCHAR(16) NOT NULL,
      cycle_count INT NOT NULL,
      price_fen BIGINT NOT NULL,
      original_price_fen BIGINT,
      grant_points BIGINT NOT NULL DEFAULT 0,
      status VARCHAR(16) NOT NULL,
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL,
      CONSTRAINT uk_price_code UNIQUE (price_code)
    );

    CREATE TABLE IF NOT EXISTS user_subscription (
      id BIGINT PRIMARY KEY,
      user_id BIGINT NOT NULL,
      plan_id BIGINT NOT NULL,
      price_code VARCHAR(32) NOT NULL,
      status VARCHAR(16) NOT NULL,
      current_period_start TIMESTAMP NOT NULL,
      current_period_end TIMESTAMP NOT NULL,
      auto_renew SMALLINT NOT NULL DEFAULT 0,
      latest_order_no VARCHAR(40),
      version INT NOT NULL DEFAULT 0,
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL,
      CONSTRAINT uk_subscription_user UNIQUE (user_id)
    );

    CREATE TABLE IF NOT EXISTS payment_order (
      id BIGINT PRIMARY KEY,
      order_no VARCHAR(40) NOT NULL,
      user_id BIGINT NOT NULL,
      order_type VARCHAR(20) NOT NULL,
      product_code VARCHAR(32) NOT NULL,
      product_name VARCHAR(100) NOT NULL,
      product_snapshot_json TEXT NOT NULL,
      amount_fen BIGINT NOT NULL,
      currency CHAR(3) NOT NULL DEFAULT 'CNY',
      status VARCHAR(16) NOT NULL,
      expire_at TIMESTAMP NOT NULL,
      paid_at TIMESTAMP,
      idempotency_key VARCHAR(64) NOT NULL,
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL,
      CONSTRAINT uk_order_no UNIQUE (order_no),
      CONSTRAINT uk_user_idempotency UNIQUE (user_id, idempotency_key)
    );

    CREATE TABLE IF NOT EXISTS payment_transaction (
      id BIGINT PRIMARY KEY,
      transaction_no VARCHAR(40) NOT NULL,
      order_no VARCHAR(40) NOT NULL,
      pay_type VARCHAR(16) NOT NULL,
      channel_transaction_no VARCHAR(64),
      status VARCHAR(16) NOT NULL,
      pay_payload TEXT,
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL,
      CONSTRAINT uk_transaction_no UNIQUE (transaction_no),
      CONSTRAINT uk_order_pay_type UNIQUE (order_no, pay_type)
    );

    CREATE TABLE IF NOT EXISTS prompt_template (
      id BIGINT PRIMARY KEY,
      template_code VARCHAR(64) NOT NULL,
      template_name VARCHAR(128) NOT NULL,
      scene VARCHAR(32) NOT NULL,
      content TEXT NOT NULL,
      status VARCHAR(16) NOT NULL,
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL,
      CONSTRAINT uk_prompt_template_code UNIQUE (template_code)
    );
    ALTER TABLE prompt_template ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE prompt_template ADD COLUMN IF NOT EXISTS attributes JSONB NOT NULL DEFAULT '{}'::jsonb;

    CREATE TABLE IF NOT EXISTS model_config (
      id BIGINT PRIMARY KEY,
      model_code VARCHAR(64) NOT NULL,
      model_name VARCHAR(128) NOT NULL,
      task_type VARCHAR(16) NOT NULL,
      base_points BIGINT NOT NULL,
      parameters_json TEXT NOT NULL,
      status VARCHAR(16) NOT NULL,
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL,
      CONSTRAINT uk_model_config_code UNIQUE (model_code)
    );
    ALTER TABLE model_config ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE model_config ADD COLUMN IF NOT EXISTS attributes JSONB NOT NULL DEFAULT '{}'::jsonb;

    CREATE TABLE IF NOT EXISTS inspiration (
      id BIGINT PRIMARY KEY,
      title VARCHAR(128) NOT NULL,
      cover_url VARCHAR(1000) NOT NULL,
      category_code VARCHAR(32) NOT NULL,
      author_name VARCHAR(64) NOT NULL,
      author_avatar_url VARCHAR(1000),
      like_count BIGINT NOT NULL DEFAULT 0,
      view_count BIGINT NOT NULL DEFAULT 0,
      sort_no INT NOT NULL DEFAULT 0,
      status VARCHAR(16) NOT NULL,
      created_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL
    );
    ALTER TABLE inspiration ADD COLUMN IF NOT EXISTS prompt TEXT;
    ALTER TABLE inspiration ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE inspiration ADD COLUMN IF NOT EXISTS attributes JSONB NOT NULL DEFAULT '{}'::jsonb;
    CREATE INDEX IF NOT EXISTS idx_inspiration_category_status ON inspiration(category_code, status, sort_no);

    CREATE TABLE IF NOT EXISTS invoice_application (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      invoice_no VARCHAR(40) NOT NULL,
      user_id BIGINT NOT NULL,
      order_no VARCHAR(40) NOT NULL,
      invoice_title VARCHAR(128) NOT NULL,
      tax_no VARCHAR(64) NOT NULL,
      invoice_type VARCHAR(32) NOT NULL,
      amount_fen BIGINT NOT NULL,
      status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
      email VARCHAR(128),
      receiver_name VARCHAR(64),
      receiver_phone VARCHAR(20),
      receiver_address VARCHAR(500),
      reject_reason VARCHAR(500),
      issued_at TIMESTAMP,
      invoice_file_asset_id BIGINT,
      express_company VARCHAR(64),
      express_no VARCHAR(64),
      gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      deleted BOOLEAN NOT NULL DEFAULT FALSE,
      attributes JSONB NOT NULL DEFAULT '{}'::jsonb
    );

    CREATE TABLE IF NOT EXISTS content_category (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      category_code VARCHAR(32) NOT NULL,
      category_name VARCHAR(64) NOT NULL,
      scope VARCHAR(32) NOT NULL,
      parent_code VARCHAR(32),
      sort_no INT NOT NULL DEFAULT 0,
      status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
      gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      deleted BOOLEAN NOT NULL DEFAULT FALSE,
      attributes JSONB NOT NULL DEFAULT '{}'::jsonb
    );

    CREATE TABLE IF NOT EXISTS admin_operation_log (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      admin_user_id BIGINT NOT NULL,
      action VARCHAR(64) NOT NULL,
      target_type VARCHAR(64) NOT NULL,
      target_id VARCHAR(64),
      request_method VARCHAR(10),
      request_path VARCHAR(255),
      before_json JSONB,
      after_json JSONB,
      remark VARCHAR(500),
      ip VARCHAR(64),
      user_agent VARCHAR(500),
      gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      deleted BOOLEAN NOT NULL DEFAULT FALSE,
      attributes JSONB NOT NULL DEFAULT '{}'::jsonb
    );
  `);
}

export async function hydratePostgresBusinessStore(pool) {
  resetBusinessStore();
  await hydrateUsers(pool);
  await hydratePlans(pool);
  await hydrateModels(pool);
  await hydrateInspirations(pool);
  await hydrateProjects(pool);
  await hydrateAssets(pool);
  await hydrateAi(pool);
  await hydrateChat(pool);
  await hydrateWorkflows(pool);
  await hydrateBilling(pool);
  await hydrateAdminContent(pool);
  const shouldPersistSeeds = SEED_BACKED_KEYS.some((key) => store[key].size === 0);
  reseedStore();
  return shouldPersistSeeds;
}

function resetBusinessStore() {
  for (const key of BUSINESS_STORE_KEYS) {
    store[key].clear();
  }
}

async function hydrateUsers(pool) {
  const users = await rows(pool, `SELECT * FROM user_account`);
  for (const row of users) {
    store.users.set(stringId(row.id), {
      id: stringId(row.id),
      phone: row.phone,
      wechatOpenId: row.wechat_open_id,
      nickname: row.nickname,
      avatarUrl: row.avatar_url,
      email: row.email,
      gender: row.gender,
      birthday: isoDate(row.birthday),
      status: row.status,
      role: row.role,
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }

  const accounts = await rows(pool, `SELECT * FROM point_account`);
  for (const row of accounts) {
    store.pointAccounts.set(stringId(row.user_id), {
      userId: stringId(row.user_id),
      availablePoints: number(row.available_points),
      frozenPoints: number(row.frozen_points),
      grantedTotal: number(row.granted_total),
      version: number(row.version),
      updatedAt: isoDate(row.updated_at)
    });
  }

  const ledgers = await rows(pool, `SELECT * FROM point_ledger`);
  for (const row of ledgers) {
    store.pointLedgers.set(stringId(row.id), {
      id: stringId(row.id),
      userId: stringId(row.user_id),
      action: row.action,
      amount: number(row.amount),
      balanceAfter: number(row.balance_after),
      bizType: row.biz_type,
      bizId: row.biz_id,
      description: row.description,
      createdAt: isoDate(row.created_at)
    });
  }
}

async function hydratePlans(pool) {
  const plans = await rows(pool, `SELECT * FROM subscription_plan`);
  for (const row of plans) {
    store.plans.set(stringId(row.id), {
      id: stringId(row.id),
      planCode: row.plan_code,
      planName: row.plan_name,
      description: row.description,
      benefits: jsonValue(row.benefits_json, []),
      status: row.status,
      deleted: boolean(row.deleted),
      attributes: jsonValue(row.attributes, {}),
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }

  const prices = await rows(pool, `SELECT * FROM subscription_plan_price`);
  for (const row of prices) {
    store.prices.set(row.price_code, {
      id: stringId(row.id),
      planId: stringId(row.plan_id),
      priceCode: row.price_code,
      cycleUnit: row.cycle_unit,
      cycleCount: number(row.cycle_count),
      priceFen: number(row.price_fen),
      originalPriceFen: nullableNumber(row.original_price_fen),
      grantPoints: number(row.grant_points),
      status: row.status,
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }
}

async function hydrateModels(pool) {
  const models = await rows(pool, `SELECT * FROM model_config`);
  for (const row of models) {
    store.models.set(row.model_code, {
      id: stringId(row.id),
      modelCode: row.model_code,
      modelName: row.model_name,
      taskType: row.task_type,
      basePoints: number(row.base_points),
      parameters: jsonValue(row.parameters_json, {}),
      status: row.status,
      deleted: boolean(row.deleted),
      attributes: jsonValue(row.attributes, {}),
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }
}

async function hydrateInspirations(pool) {
  const inspirations = await rows(pool, `SELECT * FROM inspiration`);
  for (const row of inspirations) {
    store.inspirations.set(stringId(row.id), {
      id: stringId(row.id),
      title: row.title,
      coverUrl: row.cover_url,
      categoryCode: row.category_code,
      authorName: row.author_name,
      authorAvatarUrl: row.author_avatar_url,
      likeCount: number(row.like_count),
      viewCount: number(row.view_count),
      sortNo: number(row.sort_no),
      prompt: row.prompt,
      status: row.status,
      deleted: boolean(row.deleted),
      attributes: jsonValue(row.attributes, {}),
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }
}

async function hydrateProjects(pool) {
  const projects = await rows(pool, `SELECT * FROM project`);
  for (const row of projects) {
    store.projects.set(stringId(row.id), {
      id: stringId(row.id),
      userId: stringId(row.user_id),
      title: row.title,
      coverAssetId: nullableId(row.cover_asset_id),
      status: row.status,
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }

  const canvases = await rows(pool, `SELECT * FROM project_canvas`);
  for (const row of canvases) {
    store.canvases.set(stringId(row.project_id), {
      projectId: stringId(row.project_id),
      canvas: jsonValue(row.canvas_json, {}),
      revision: number(row.revision),
      updatedAt: isoDate(row.updated_at)
    });
  }

  const groups = await rows(pool, `SELECT * FROM canvas_element_group`);
  for (const row of groups) {
    store.canvasElementGroups.set(stringId(row.id), {
      id: stringId(row.id),
      userId: stringId(row.user_id),
      projectId: stringId(row.project_id),
      name: row.name,
      description: row.description,
      structure: jsonValue(row.structure_json, {}),
      deleted: boolean(row.deleted),
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }

  const versions = await rows(pool, `SELECT * FROM project_version`);
  for (const row of versions) {
    store.versions.set(stringId(row.id), {
      id: stringId(row.id),
      projectId: stringId(row.project_id),
      versionNo: number(row.version_no),
      canvas: jsonValue(row.canvas_json, {}),
      createdAt: isoDate(row.created_at)
    });
  }

  const shares = await rows(pool, `SELECT * FROM project_share`);
  for (const row of shares) {
    const project = store.projects.get(stringId(row.project_id));
    store.shares.set(row.share_code, {
      shareCode: row.share_code,
      projectId: stringId(row.project_id),
      userId: stringId(row.user_id),
      title: row.title || project?.title || "分享项目",
      expireAt: isOpenEnded(row.expire_at) ? null : isoDate(row.expire_at),
      status: row.status,
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at || row.created_at)
    });
  }
}

async function hydrateAssets(pool) {
  const assets = await rows(pool, `SELECT * FROM asset`);
  for (const row of assets) {
    store.assets.set(stringId(row.id), {
      id: stringId(row.id),
      userId: stringId(row.user_id),
      projectId: nullableId(row.project_id),
      type: row.type,
      source: row.source,
      fileName: row.file_name,
      objectKey: row.object_key,
      contentType: row.content_type,
      fileSize: nullableNumber(row.file_size),
      width: nullableNumber(row.width),
      height: nullableNumber(row.height),
      durationSeconds: nullableNumber(row.duration_seconds),
      reviewStatus: row.deleted ? "DELETED" : row.review_status,
      previewUrl: row.preview_url || (row.object_key ? publicObjectUrl(row.object_key) : null),
      tags: jsonValue(row.tags_json, []),
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }

  const favorites = await rows(pool, `SELECT user_id, asset_id FROM asset_favorite`);
  for (const row of favorites) {
    store.favorites.add(`${stringId(row.user_id)}:${stringId(row.asset_id)}`);
  }
}

async function hydrateAi(pool) {
  const tasks = await rows(pool, `SELECT * FROM generation_task`);
  const tasksWithResultsJson = new Set();
  for (const row of tasks) {
    const results = jsonValue(row.results_json, null);
    if (Array.isArray(results) && results.length > 0) {
      tasksWithResultsJson.add(stringId(row.id));
    }
    store.generationTasks.set(stringId(row.id), {
      id: stringId(row.id),
      userId: stringId(row.user_id),
      projectId: nullableId(row.project_id),
      nodeId: row.node_id,
      taskType: row.task_type,
      capabilityCode: row.capability_code,
      prompt: row.prompt || "",
      parameters: jsonValue(row.parameters_json, {}),
      referenceAssetIds: jsonValue(row.reference_asset_ids_json, []),
      idempotencyKey: row.idempotency_key,
      providerTaskId: row.provider_task_id,
      status: row.status,
      progress: number(row.progress),
      estimatedPoints: number(row.estimated_points),
      actualPoints: nullableNumber(row.actual_points),
      error: row.error_code || row.error_message ? { code: row.error_code, message: row.error_message } : null,
      results: Array.isArray(results) ? results : [],
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }

  const results = await rows(pool, `SELECT * FROM generation_result ORDER BY task_id, sort_no`);
  for (const row of results) {
    const task = store.generationTasks.get(stringId(row.task_id));
    if (!task) continue;
    if (tasksWithResultsJson.has(task.id)) continue;
    const asset = store.assets.get(stringId(row.asset_id));
    task.results.push({
      assetId: stringId(row.asset_id),
      type: asset?.type || task.taskType
    });
  }
}

async function hydrateChat(pool) {
  const sessions = await rows(pool, `SELECT * FROM chat_session`);
  for (const row of sessions) {
    store.chatSessions.set(stringId(row.id), {
      id: stringId(row.id),
      userId: stringId(row.user_id),
      projectId: nullableId(row.project_id),
      title: row.title,
      deleted: boolean(row.deleted),
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }

  const messages = await rows(pool, `SELECT * FROM chat_message`);
  for (const row of messages) {
    store.chatMessages.set(stringId(row.id), {
      id: stringId(row.id),
      sessionId: stringId(row.session_id),
      role: row.role,
      content: row.content,
      attachmentAssetIds: jsonValue(row.attachment_asset_ids_json, []),
      generationTaskIds: jsonValue(row.generation_task_ids_json, []),
      createdAt: isoDate(row.created_at)
    });
  }
}

async function hydrateWorkflows(pool) {
  const workflows = await rows(pool, `SELECT * FROM workflow`);
  for (const row of workflows) {
    store.workflows.set(stringId(row.id), {
      id: stringId(row.id),
      userId: nullableId(row.user_id),
      name: row.name,
      description: row.description,
      coverAssetId: nullableId(row.cover_asset_id),
      workflowData: jsonValue(row.workflow_json, {}),
      deleted: boolean(row.deleted),
      attributes: jsonValue(row.attributes, {}),
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }
}

async function hydrateBilling(pool) {
  const orders = await rows(pool, `SELECT * FROM payment_order`);
  for (const row of orders) {
    store.orders.set(row.order_no, {
      id: stringId(row.id),
      orderNo: row.order_no,
      userId: stringId(row.user_id),
      orderType: row.order_type,
      productCode: row.product_code,
      productName: row.product_name,
      productSnapshot: jsonValue(row.product_snapshot_json, {}),
      amountFen: number(row.amount_fen),
      currency: row.currency,
      status: row.status,
      expireAt: isoDate(row.expire_at),
      paidAt: isoDate(row.paid_at),
      idempotencyKey: row.idempotency_key,
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }

  const transactions = await rows(pool, `SELECT * FROM payment_transaction`);
  for (const row of transactions) {
    const payload = jsonValue(row.pay_payload, {});
    store.transactions.set(`${row.order_no}:${row.pay_type}`, {
      id: stringId(row.id),
      transactionNo: row.transaction_no,
      orderNo: row.order_no,
      payType: row.pay_type,
      channelTransactionNo: row.channel_transaction_no,
      status: row.status,
      qrCodeContent: payload.qrCodeContent,
      redirectUrl: payload.redirectUrl,
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }

  const subscriptions = await rows(pool, `
    SELECT us.*, sp.plan_code, sp.plan_name
      FROM user_subscription us
      LEFT JOIN subscription_plan sp ON sp.id = us.plan_id
  `);
  for (const row of subscriptions) {
    store.subscriptions.set(stringId(row.user_id), {
      planCode: row.plan_code,
      planName: row.plan_name,
      priceCode: row.price_code,
      status: row.status,
      currentPeriodStart: isoDate(row.current_period_start),
      currentPeriodEnd: isoDate(row.current_period_end),
      expireAt: isoDate(row.current_period_end),
      autoRenew: boolean(row.auto_renew),
      latestOrderNo: row.latest_order_no,
      version: number(row.version),
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }
}

async function hydrateAdminContent(pool) {
  const templates = await rows(pool, `SELECT * FROM prompt_template`);
  for (const row of templates) {
    store.promptTemplates.set(row.template_code, {
      id: stringId(row.id),
      code: row.template_code,
      name: row.template_name,
      scene: row.scene,
      scenario: row.scene,
      content: row.content,
      status: row.status,
      deleted: boolean(row.deleted),
      attributes: jsonValue(row.attributes, {}),
      createdAt: isoDate(row.created_at),
      updatedAt: isoDate(row.updated_at)
    });
  }

  const categories = await rows(pool, `SELECT * FROM content_category`);
  for (const row of categories) {
    store.contentCategories.set(row.category_code, {
      id: stringId(row.id),
      categoryCode: row.category_code,
      categoryName: row.category_name,
      scope: row.scope,
      parentCode: row.parent_code,
      sortNo: number(row.sort_no),
      status: row.status,
      deleted: boolean(row.deleted),
      attributes: jsonValue(row.attributes, {}),
      createdAt: isoDate(row.gmt_create),
      updatedAt: isoDate(row.gmt_modified)
    });
  }

  const invoices = await rows(pool, `SELECT * FROM invoice_application`);
  for (const row of invoices) {
    store.invoiceApplications.set(stringId(row.id), {
      id: stringId(row.id),
      invoiceNo: row.invoice_no,
      userId: stringId(row.user_id),
      orderNo: row.order_no,
      invoiceTitle: row.invoice_title,
      taxNo: row.tax_no,
      invoiceType: row.invoice_type,
      amountFen: number(row.amount_fen),
      status: row.status,
      email: row.email,
      receiverName: row.receiver_name,
      receiverPhone: row.receiver_phone,
      receiverAddress: row.receiver_address,
      rejectReason: row.reject_reason,
      issuedAt: isoDate(row.issued_at),
      invoiceFileAssetId: nullableId(row.invoice_file_asset_id),
      expressCompany: row.express_company,
      expressNo: row.express_no,
      deleted: boolean(row.deleted),
      attributes: jsonValue(row.attributes, {}),
      createdAt: isoDate(row.gmt_create),
      updatedAt: isoDate(row.gmt_modified)
    });
  }

  const logs = await rows(pool, `SELECT * FROM admin_operation_log`);
  for (const row of logs) {
    store.adminOperationLogs.set(stringId(row.id), {
      id: stringId(row.id),
      adminUserId: stringId(row.admin_user_id),
      action: row.action,
      targetType: row.target_type,
      targetId: row.target_id,
      before: jsonValue(row.before_json, null),
      after: jsonValue(row.after_json, null),
      remark: row.remark,
      deleted: boolean(row.deleted),
      attributes: jsonValue(row.attributes, {}),
      createdAt: isoDate(row.gmt_create),
      updatedAt: isoDate(row.gmt_modified)
    });
  }
}

async function rows(pool, sql, values = []) {
  const result = await pool.query(sql, values);
  return result.rows;
}

function stringId(value) {
  return String(value);
}

function nullableId(value) {
  return value === undefined || value === null || value === "" || Number(value) === 0 ? null : String(value);
}

function number(value) {
  return Number(value || 0);
}

function nullableNumber(value) {
  return value === undefined || value === null || value === "" ? null : Number(value);
}

function boolean(value) {
  return value === true || value === 1 || value === "1" || value === "true";
}

function isoDate(value) {
  return value ? new Date(value).toISOString() : null;
}

function jsonValue(value, fallback) {
  if (value === undefined || value === null || value === "") {
    return fallback;
  }
  if (typeof value === "object") {
    return value;
  }
  try {
    return JSON.parse(value);
  } catch {
    return fallback;
  }
}

function isOpenEnded(value) {
  return value && new Date(value).getFullYear() >= 2999;
}

function publicObjectUrl(objectKey) {
  const baseUrl = appConfig.storage.publicBaseUrl || "/api/mock-files";
  return `${baseUrl.replace(/\/$/, "")}/${String(objectKey).split("/").map(encodeURIComponent).join("/")}`;
}
